// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnthqkdsmdwekjecxccn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudGhxa2RzbWR3ZWtqZWN4Y2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjUwMDYsImV4cCI6MjA2NjAwMTAwNn0.U-1vULaqjPwed97XIrUFu7znEq_VViyELi0rbtvwo1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);